/* Generated By:JavaCC: Do not edit this line. compilador.java */
package comp;
public class compilador implements compiladorConstants {

//VOID PARA QUE NO RETORNE 
  final public void Principal() throws ParseException {
    jj_consume_token(PR_PUB);
    jj_consume_token(PR_CLS);
    jj_consume_token(IDENTIFICADOR);
    jj_consume_token(OTROS_LLAVEINI);
    Body();
    jj_consume_token(OTROS_LLAVEFIN);
    jj_consume_token(OTROS_DOSPUN);
    jj_consume_token(0);
  }

  final public void Body() throws ParseException {
    if (jj_2_1(2)) {
      Estructura();
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PR_PUB:
        VariablesGlobales();
        break;
      default:
        jj_la1[0] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

  final public void Estructura() throws ParseException {
    jj_consume_token(PR_PUB);
    jj_consume_token(PR_STC);
    jj_consume_token(PR_VOID);
    jj_consume_token(PR_MAIN);
    jj_consume_token(OTROS_LLAVEINI);
    Sentencias();
    jj_consume_token(OTROS_LLAVEFIN);
  }

  final public void VariablesGlobales() throws ParseException {
    jj_consume_token(PR_PUB);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case TIPDAT_INT:
    case TIPDAT_LONG:
    case TIPDAT_BYTE:
      DeclaraEnteros();
      break;
    case TIPDAT_FLO:
    case TIPDAT_BOOLE:
      DeclaraFlotantes();
      break;
    case TIPDAT_STR:
      DeclaraCadenas();
      break;
    default:
      jj_la1[1] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    Body();
  }

  final public void DeclaraEnteros() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case TIPDAT_INT:
      jj_consume_token(TIPDAT_INT);
      break;
    case TIPDAT_LONG:
      jj_consume_token(TIPDAT_LONG);
      break;
    case TIPDAT_BYTE:
      jj_consume_token(TIPDAT_BYTE);
      break;
    default:
      jj_la1[2] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(IDENTIFICADOR);
    jj_consume_token(OTROS_ASIG);
    jj_consume_token(NUMERO);
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case OTROS_COMA:
        ;
        break;
      default:
        jj_la1[3] = jj_gen;
        break label_1;
      }
      jj_consume_token(OTROS_COMA);
      jj_consume_token(IDENTIFICADOR);
      jj_consume_token(OTROS_ASIG);
      jj_consume_token(NUMERO);
    }
    jj_consume_token(OTROS_DOSPUN);
  }

  final public void DeclaraFlotantes() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case TIPDAT_FLO:
      jj_consume_token(TIPDAT_FLO);
      break;
    case TIPDAT_BOOLE:
      jj_consume_token(TIPDAT_BOOLE);
      break;
    default:
      jj_la1[4] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(IDENTIFICADOR);
    jj_consume_token(OTROS_ASIG);
    jj_consume_token(NUMBER);
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case OTROS_COMA:
        ;
        break;
      default:
        jj_la1[5] = jj_gen;
        break label_2;
      }
      jj_consume_token(OTROS_COMA);
      jj_consume_token(IDENTIFICADOR);
      jj_consume_token(OTROS_ASIG);
      jj_consume_token(NUMBER);
    }
    jj_consume_token(OTROS_DOSPUN);
  }

  final public void DeclaraCadenas() throws ParseException {
    jj_consume_token(TIPDAT_STR);
    jj_consume_token(IDENTIFICADOR);
    jj_consume_token(OTROS_ASIG);
    jj_consume_token(OTROS_COMDOB);
    jj_consume_token(IDENTIFICADOR);
    jj_consume_token(OTROS_COMDOB);
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case OTROS_COMA:
        ;
        break;
      default:
        jj_la1[6] = jj_gen;
        break label_3;
      }
      jj_consume_token(OTROS_COMA);
      jj_consume_token(IDENTIFICADOR);
      jj_consume_token(OTROS_ASIG);
      jj_consume_token(OTROS_COMDOB);
      jj_consume_token(IDENTIFICADOR);
      jj_consume_token(OTROS_COMDOB);
    }
    jj_consume_token(OTROS_DOSPUN);
  }

  final public void EstructuraMetodo() throws ParseException {
    jj_consume_token(PR_PUB);
    jj_consume_token(IDENTIFICADOR);
    jj_consume_token(OTROS_PARENABRIR);
    jj_consume_token(OTROS_PARENCIERRE);
    jj_consume_token(OTROS_LLAVEINI);
    LocalVariables();
    jj_consume_token(OTROS_LLAVEFIN);
  }

  final public void LocalVariables() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case TIPDAT_STR:
      jj_consume_token(TIPDAT_STR);
      break;
    case TIPDAT_CHAR:
      jj_consume_token(TIPDAT_CHAR);
      break;
    case TIPDAT_INT:
      jj_consume_token(TIPDAT_INT);
      break;
    case TIPDAT_DOU:
      jj_consume_token(TIPDAT_DOU);
      break;
    case TIPDAT_FLO:
      jj_consume_token(TIPDAT_FLO);
      break;
    case TIPDAT_LONG:
      jj_consume_token(TIPDAT_LONG);
      jj_consume_token(TIPDAT_BYTE);
      break;
    case TIPDAT_BOOLE:
      jj_consume_token(TIPDAT_BOOLE);
      break;
    default:
      jj_la1[7] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(IDENTIFICADOR);
    jj_consume_token(OTROS_DOSPUN);
  }

  final public void Sentencias() throws ParseException {
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PR_SYS:
      case PR_PUB:
      case CICL_WHI:
      case CICL_FOR:
      case CONDI_IF:
      case OTROS_PARENABRIR:
      case PrintInt:
      case PrintString:
      case PrintBoolean:
      case PrintChar:
      case PrintFloat:
        ;
        break;
      default:
        jj_la1[8] = jj_gen;
        break label_4;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case CONDI_IF:
        SentenciaIf();
        break;
      case PR_SYS:
        Imprimir();
        break;
      case CICL_WHI:
        Ciclo_While();
        break;
      case CICL_FOR:
        Ciclo_For();
        break;
      case PR_PUB:
        EstructuraMetodo();
        break;
      case OTROS_PARENABRIR:
        ExpresionesAritmeticas();
        break;
      case PrintInt:
      case PrintString:
      case PrintBoolean:
      case PrintChar:
      case PrintFloat:
        ImprimirValores();
        break;
      default:
        jj_la1[9] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

  final public void SentenciaIf() throws ParseException {
    jj_consume_token(CONDI_IF);
    jj_consume_token(OTROS_PARENABRIR);
    AceptaBooleanos();
    jj_consume_token(OTROS_PARENCIERRE);
    jj_consume_token(OTROS_LLAVEINI);
    Sentencias();
    jj_consume_token(OTROS_LLAVEFIN);
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case CONDI_ELSE:
        ;
        break;
      default:
        jj_la1[10] = jj_gen;
        break label_5;
      }
      Sino();
    }
  }

  final public void AceptaBooleanos() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENTIFICADOR:
      jj_consume_token(IDENTIFICADOR);
      break;
    case NUMERO:
      jj_consume_token(NUMERO);
      break;
    default:
      jj_la1[11] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case OPE_MENOR:
      jj_consume_token(OPE_MENOR);
      break;
    case OPE_MAYOR:
      jj_consume_token(OPE_MAYOR);
      break;
    case OPE_DOBLEIGUAL:
      jj_consume_token(OPE_DOBLEIGUAL);
      break;
    case OPE_MENORIGUAL:
      jj_consume_token(OPE_MENORIGUAL);
      break;
    case OPE_MAYORIGUAL:
      jj_consume_token(OPE_MAYORIGUAL);
      break;
    case OPE_DIFERENTE:
      jj_consume_token(OPE_DIFERENTE);
      break;
    case OPE_AND:
      jj_consume_token(OPE_AND);
      break;
    case OPE_OR:
      jj_consume_token(OPE_OR);
      break;
    default:
      jj_la1[12] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENTIFICADOR:
      jj_consume_token(IDENTIFICADOR);
      break;
    case NUMERO:
      jj_consume_token(NUMERO);
      break;
    case NUMBER:
      jj_consume_token(NUMBER);
      break;
    default:
      jj_la1[13] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case OPE_AND:
      case OPE_OR:
        ;
        break;
      default:
        jj_la1[14] = jj_gen;
        break label_6;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case OPE_AND:
        jj_consume_token(OPE_AND);
        break;
      case OPE_OR:
        jj_consume_token(OPE_OR);
        break;
      default:
        jj_la1[15] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IDENTIFICADOR:
        jj_consume_token(IDENTIFICADOR);
        break;
      case NUMERO:
        jj_consume_token(NUMERO);
        break;
      default:
        jj_la1[16] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case OPE_MENOR:
        jj_consume_token(OPE_MENOR);
        break;
      case OPE_MAYOR:
        jj_consume_token(OPE_MAYOR);
        break;
      case OPE_DOBLEIGUAL:
        jj_consume_token(OPE_DOBLEIGUAL);
        break;
      case OPE_MENORIGUAL:
        jj_consume_token(OPE_MENORIGUAL);
        break;
      case OPE_MAYORIGUAL:
        jj_consume_token(OPE_MAYORIGUAL);
        break;
      case OPE_DIFERENTE:
        jj_consume_token(OPE_DIFERENTE);
        break;
      case OPE_AND:
        jj_consume_token(OPE_AND);
        break;
      case OPE_OR:
        jj_consume_token(OPE_OR);
        break;
      default:
        jj_la1[17] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IDENTIFICADOR:
        jj_consume_token(IDENTIFICADOR);
        break;
      case NUMERO:
        jj_consume_token(NUMERO);
        break;
      default:
        jj_la1[18] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

  final public void Sino() throws ParseException {
    jj_consume_token(CONDI_ELSE);
    jj_consume_token(OTROS_PARENABRIR);
    jj_consume_token(OTROS_PARENCIERRE);
    jj_consume_token(OTROS_LLAVEINI);
    jj_consume_token(OTROS_LLAVEFIN);
  }

  final public void Ciclo_While() throws ParseException {
    jj_consume_token(CICL_WHI);
    jj_consume_token(OTROS_PARENABRIR);
    AceptaBooleanos();
    jj_consume_token(OTROS_PARENCIERRE);
    jj_consume_token(OTROS_LLAVEINI);
    Sentencias();
    jj_consume_token(OTROS_LLAVEFIN);
  }

  final public void Ciclo_For() throws ParseException {
    jj_consume_token(CICL_FOR);
    jj_consume_token(OTROS_PARENABRIR);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case TIPDAT_INT:
      jj_consume_token(TIPDAT_INT);
      break;
    default:
      jj_la1[19] = jj_gen;
      ;
    }
    jj_consume_token(IDENTIFICADOR);
    jj_consume_token(OTROS_ASIG);
    jj_consume_token(NUMERO);
    jj_consume_token(OTROS_DOSPUN);
    AceptaBooleanos();
    jj_consume_token(OTROS_DOSPUN);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENTIFICADOR:
      jj_consume_token(IDENTIFICADOR);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case OPEARI_DECREMENTO:
        jj_consume_token(OPEARI_DECREMENTO);
        break;
      case OPEARI_INCREMENTO:
        jj_consume_token(OPEARI_INCREMENTO);
        break;
      default:
        jj_la1[20] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[21] = jj_gen;
      ;
    }
    jj_consume_token(OTROS_PARENCIERRE);
    jj_consume_token(OTROS_LLAVEINI);
    Sentencias();
    jj_consume_token(OTROS_LLAVEFIN);
  }

  final public void Imprimir() throws ParseException {
    jj_consume_token(PR_SYS);
    jj_consume_token(PR_OUT);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case PR_PRT:
      jj_consume_token(PR_PRT);
      break;
    case PR_PRTL:
      jj_consume_token(PR_PRTL);
      break;
    default:
      jj_la1[22] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(OTROS_PARENABRIR);
    ImprimirNumeroTexto();
    jj_consume_token(OTROS_PARENCIERRE);
    jj_consume_token(OTROS_DOSPUN);
  }

  final public void ExpresionesAritmeticas() throws ParseException {
    jj_consume_token(OTROS_PARENABRIR);
    ValidaExpresionesAritmeticas();
    jj_consume_token(OTROS_PARENCIERRE);
  }

  final public void ValidaExpresionesAritmeticas() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case OPEARI_SUMA:
    case OPEARI_RESTA:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case OPEARI_SUMA:
        jj_consume_token(OPEARI_SUMA);
        break;
      case OPEARI_RESTA:
        jj_consume_token(OPEARI_RESTA);
        break;
      default:
        jj_la1[23] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[24] = jj_gen;
      ;
    }
    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NUMERO:
        ;
        break;
      default:
        jj_la1[25] = jj_gen;
        break label_7;
      }
      jj_consume_token(NUMERO);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case OPEARI_SUMA:
      case OPEARI_RESTA:
      case OPEARI_DIV:
      case OPEARI_MODULAR:
      case OPEARI_MULTI:
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case OPEARI_SUMA:
          jj_consume_token(OPEARI_SUMA);
          break;
        case OPEARI_RESTA:
          jj_consume_token(OPEARI_RESTA);
          break;
        case OPEARI_DIV:
          jj_consume_token(OPEARI_DIV);
          break;
        case OPEARI_MULTI:
          jj_consume_token(OPEARI_MULTI);
          break;
        case OPEARI_MODULAR:
          jj_consume_token(OPEARI_MODULAR);
          break;
        default:
          jj_la1[26] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        break;
      default:
        jj_la1[27] = jj_gen;
        ;
      }
    }
  }

  final public void ImprimirNumeroTexto() throws ParseException {
    label_8:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case OTROS_COMDOB:
        jj_consume_token(OTROS_COMDOB);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case IDENTIFICADOR:
          jj_consume_token(IDENTIFICADOR);
          break;
        case NUMERO:
          jj_consume_token(NUMERO);
          break;
        default:
          jj_la1[28] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        jj_consume_token(OTROS_COMDOB);
        break;
      case NUMERO:
        jj_consume_token(NUMERO);
        break;
      default:
        jj_la1[29] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case OTROS_COMDOB:
      case NUMERO:
        ;
        break;
      default:
        jj_la1[30] = jj_gen;
        break label_8;
      }
    }
  }

  final public void ImprimirValores() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case PrintInt:
      jj_consume_token(PrintInt);
      break;
    case PrintFloat:
      jj_consume_token(PrintFloat);
      break;
    case PrintChar:
      jj_consume_token(PrintChar);
      break;
    case PrintBoolean:
      jj_consume_token(PrintBoolean);
      break;
    case PrintString:
      jj_consume_token(PrintString);
      break;
    default:
      jj_la1[31] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(IDENTIFICADOR);
    jj_consume_token(OTROS_DOSPUN);
  }

  private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_3_1() {
    if (jj_3R_9()) return true;
    return false;
  }

  private boolean jj_3R_9() {
    if (jj_scan_token(PR_PUB)) return true;
    if (jj_scan_token(PR_STC)) return true;
    return false;
  }

  /** Generated Token Manager. */
  public compiladorTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  private int jj_gen;
  final private int[] jj_la1 = new int[32];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
      jj_la1_init_2();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x100,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x2c000104,0x2c000104,0x10000000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x30,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x0,0x3d4,0xc4,0x0,0x110,0x0,0x0,0x37c,0x0,0x0,0x0,0x0,0x7f8000,0x0,0x600000,0x600000,0x0,0x7f8000,0x0,0x4,0x30000000,0x0,0x0,0x1800000,0x1800000,0x0,0xf800000,0xf800000,0x0,0x0,0x0,0x0,};
   }
   private static void jj_la1_init_2() {
      jj_la1_2 = new int[] {0x0,0x0,0x0,0x400,0x0,0x400,0x400,0x0,0xf810,0xf810,0x0,0x30000,0x0,0x70000,0x0,0x0,0x30000,0x0,0x30000,0x0,0x0,0x20000,0x0,0x0,0x0,0x10000,0x0,0x0,0x30000,0x10080,0x10080,0xf800,};
   }
  final private JJCalls[] jj_2_rtns = new JJCalls[1];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public compilador(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public compilador(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new compiladorTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 32; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 32; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public compilador(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new compiladorTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 32; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 32; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public compilador(compiladorTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 32; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(compiladorTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 32; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      jj_entries_loop: for (java.util.Iterator<?> it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              continue jj_entries_loop;
            }
          }
          jj_expentries.add(jj_expentry);
          break jj_entries_loop;
        }
      }
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[89];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 32; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
          if ((jj_la1_2[i] & (1<<j)) != 0) {
            la1tokens[64+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 89; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 1; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
